// utils/constants.js
const ROLES = {
  ADMIN: "admin",
  SECURITY: "security",
  EMPLOYEE: "employee",
  VISITOR: "visitor",
};

const VISITOR_STATUSES = {
  PENDING: "pending",
  APPROVED: "approved",
  REJECTED: "rejected",
  CHECKED_IN: "checked-in",
  CHECKED_OUT: "checked-out",
};

const APPOINTMENT_STATUSES = {
  PENDING: "pending",
  APPROVED: "approved",
  REJECTED: "rejected",
  CANCELLED: "cancelled",
};

const CHECK_ACTIONS = {
  CHECK_IN: "check-in",
  CHECK_OUT: "check-out",
};

const AUDIT_ACTIONS = {
  USER_REGISTERED: "USER_REGISTERED",
  BOOTSTRAP_ADMIN: "BOOTSTRAP_ADMIN",
  VISITOR_CREATED: "VISITOR_CREATED",
  VISITOR_SOFT_DELETED: "VISITOR_SOFT_DELETED",
  VISITOR_APPROVED: "VISITOR_APPROVED",
  VISITOR_REJECTED: "VISITOR_REJECTED",
  APPOINTMENT_CREATED: "APPOINTMENT_CREATED",
  APPOINTMENT_CANCELLED: "APPOINTMENT_CANCELLED",
  APPOINTMENT_APPROVED: "APPOINTMENT_APPROVED",
  APPOINTMENT_PRE_REGISTERED: "APPOINTMENT_PRE_REGISTERED",
  PASS_ISSUED: "PASS_ISSUED",
  PASS_DEACTIVATED: "PASS_DEACTIVATED",
  CHECK_IN: "CHECK_IN",
  CHECK_OUT: "CHECK_OUT",
};

module.exports = {
  ROLES,
  VISITOR_STATUSES,
  APPOINTMENT_STATUSES,
  CHECK_ACTIONS,
  AUDIT_ACTIONS,
};
